version: '3.3'

services: 
  dhis2mq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  dhis2db:
    image: mdillon/postgis:10-alpine
    env_file: .postgres.env
    volumes:
      - type: volume
        source: dhis2_db
        target: /var/lib/postgresql/data
    restart: always
  dhis2app:
    image: dhis2app:latest
    build:
      context: ./dhis2app
    volumes:
      - type: volume
        source: dhis2_home
        target: /dhis2/home
      - type: bind
        source: ./dhis.conf
        target: /dhis2/home/dhis.conf
      - type: bind
        source: ./logs/dhis2
        target: /dhis2/home/logs
      - type: bind
        source: ./logs/tomcat
        target: /usr/local/tomcat/logs
    depends_on: 
      - dhis2mq
      - dhis2db
    ports:
      - 8080:8080
    entrypoint: /wait-for -t 50000 dhis2mq:5672 -- /wait-for -t 50000 dhis2db:5432 --
    command: catalina.sh run
    restart: always

volumes:
  dhis2_db:
  dhis2_home:
